version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: misalud-precios-api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}
      - DEMO_ALLOW_ALL=${DEMO_ALLOW_ALL:-false}
      - CSV_DEFAULT_SEP=${CSV_DEFAULT_SEP:-,}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
    volumes:
      - ./app/data:/app/data
    restart: unless-stopped
