version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: misalud-precios-api
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - DEMO_ALLOW_ALL=${DEMO_ALLOW_ALL:-false}
      - CSV_DEFAULT_SEP=${CSV_DEFAULT_SEP:-,}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
    volumes:
      - ./app/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
